coverage_service: cobertura_xml
workspace: Swiftmazing.xcworkspace

scheme: SwiftmazingCodeCoverage

output_directory: fastlane/slather

xcodeproj: Swiftmazing/Swiftmazing.xcodeproj
ignore:
  - Infrastructure/InfrastructureTests/*
  - Visual/VisualTests/*
  - Swiftmazing/SwiftmazingTests/*
  - Swiftmazing/SwiftmazingFunctionalTests/*