language:
  - swift
osx_image: xcode11.3
cache:
  bundler: true
  cocoapods: true

before_install:
- rvm use $RVM_RUBY_VERSION
- gem install bundler
- bundler install
- gem install cocoapods
- pod install

install: bundle install --without=documentation --path ../travis_bundle_dir

script:
  - bundle exec fastlane tests
after_success:
  - bash <(curl -s https://codecov.io/bash) -f fastlane/slather/cobertura.xml -X coveragepy -X gcov -X xcode