name: Swiftmazing

options:
  postGenCommand: pod install --repo-update
  indentWidth: 2
  tabWidth: 2
  xcodeVersion: 0800

config:
  debug: debug
  release: release

settings:
  base:
    IPHONEOS_DEPLOYMENT_TARGET: 13

include:
  - path: xcodegen/swiftmazing.yml
    relativePaths: false
  - path: xcodegen/visual.yml
    relativePaths: false
  - path: xcodegen/infrastructure.yml
    relativePaths: false