name: Swiftmazing
packages:
  NetworkLayer:
    path: NetworkLayer
  UIComponents:
    path: UIComponents
  CombineSchedulers:
    url: https://github.com/pointfreeco/combine-schedulers
    minorVersion: 1.0.0
options:
  indentWidth: 2
  tabWidth: 2
  groupSortPosition: top
  xcodeVersion: 0800
  groupOrdering: 
    - order: [Swiftmazing, SwiftmazingTests]
config:
  debug: debug
  release: release
settings:
  base:
    IPHONEOS_DEPLOYMENT_TARGET: 15
    SWIFT_VERSION: 6.0
targets:
  Swiftmazing:
    type: application
    platform: iOS
    sources:
      - path: Swiftmazing/
    settings:
      base:
        TARGETED_DEVICE_FAMILY: 1
        DISPLAYNAME: Swiftmazing
        HOST: api.github.com
        SCHEME: https
        INFOPLIST_FILE: Swiftmazing/Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.swiftmazing
        CLANG_ENABLE_CODE_COVERAGE: YES
    dependencies:
      - package: NetworkLayer
        product: NetworkLayer
        link: true
      - package: UIComponents
        product: UIComponents
        link: true
      - package: CombineSchedulers
        product: CombineSchedulers
        link: true
    scheme:
      gatherCoverageData: true
      coverageTargets:
        - Swiftmazing
      testTargets:
        - SwiftmazingTests
  SwiftmazingTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: SwiftmazingTests
    settings:
      base:
        INFOPLIST_FILE: SwiftmazingTests/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.swiftmazingtests
    dependencies:
      - target: Swiftmazing

