name: Swiftmazing

options:
  postGenCommand: pod install --repo-update
  indentWidth: 4
  tabWidth: 4
  xcodeVersion: 0800

config:
  debug: debug
  release: release

settings:
  base:
    IPHONEOS_DEPLOYMENT_TARGET: 13

targets:
  
  Swiftmazing:
    type: application
    platform: iOS

    sources:
      - path: Swiftmazing/
        excludes:
          - "**/ServiceProviderMock.swift"

    settings:
      base:
        TARGETED_DEVICE_FAMILY: 1
        DISPLAYNAME: Swiftmazing
        HOST: api.github.com
        SCHEME: https
        INFOPLIST_FILE: Swiftmazing/Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.swiftmazing

    dependencies:
      - target: Visual
        codeSign: false
        embed: false
      - target: Infrastructure
        codeSign: false
        embed: false

  SwiftmazingMock:
    type: application
    platform: iOS

    sources:
      - path: Swiftmazing/
        excludes:
          - "**/ServiceProvider.swift"

    settings:
      base:
        TARGETED_DEVICE_FAMILY: 1
        DISPLAYNAME: Swiftmazing
        HOST: api.github.com
        SCHEME: https
        INFOPLIST_FILE: Swiftmazing/Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.swiftmazing.mock

    dependencies:
      - target: Visual
        codeSign: false
        embed: false
      - target: Infrastructure
        codeSign: false
        embed: false

  SwiftmazingFunctionalTests:
    type: bundle.unit-test
    platform: iOS

    sources:
      - path: SwiftmazingFunctionalTests

    settings:
      base:
        INFOPLIST_FILE: SwiftmazingFunctionalTests/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.swiftmazingfunctionaltests

  SwiftmazingTests:
    type: bundle.unit-test
    platform: iOS

    sources:
      - path: SwiftmazingTests

    settings:
      base:
        INFOPLIST_FILE: SwiftmazingTests/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.swiftmazingtests

  Visual:
    type: framework
    platform: iOS

    sources:
      - path: Visual

    settings:
      base:
        INFOPLIST_FILE: Visual/Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.visual

  VisualTests:
    type: bundle.unit-test
    platform: iOS

    sources:
      - path: VisualTests
        excludes:
        - "/ReferenceImages"

    settings:
      base:
        INFOPLIST_FILE: VisualTests/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.visualtests

  Infrastructure:
    type: framework
    platform: iOS

    sources:
      - path: Infrastructure

    settings:
      base:
        INFOPLIST_FILE: Infrastructure/Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.infrastructure

  InfrastructureTests:
    type: bundle.unit-test
    platform: iOS

    sources:
      - path: InfrastructureTests
    
    settings:
      base:
        INFOPLIST_FILE: InfrastructureTests/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.infrastructuretests

  
