//
//  ListViewController.swift
//  Swiftmazing
//
//  Created by Hélio Mesquita on 14/12/19.
//  Copyright (c) 2019 Hélio Mesquita. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Visual

protocol ListDisplayLogic: class {
    func show(_ viewModel: List.ViewModel)
}

class ListViewController: ListCollectionViewController<List.ListCellViewModel> {

    var interactor: ListBusinessLogic?
    var router: (ListRoutingLogic & ListDataPassing)?

    var viewModel: List.ViewModel = List.ViewModel() {
        didSet {
            reloadTable()
        }
    }

    override func setup() {
        let viewController = self
        let interactor = ListInteractor()
        let presenter = ListPresenter()
        let router = ListRouter()
        viewController.interactor = interactor
        viewController.router = router
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
        interactor.presenter = presenter
    }

    override func viewDidLoad() {
        super.viewDidLoad()
        interactor?.loadScreen()
        title = "TELA DE LISTA"
    }

    func reloadTable() {
        var snapshot = NSDiffableDataSourceSnapshot<ListSection, List.ListCellViewModel>()
        snapshot.appendSections([.repo])
        snapshot.appendItems(viewModel.items, toSection: .repo)
        dataSource.apply(snapshot, animatingDifferences: true)
        collectionView.collectionViewLayout.invalidateLayout()
    }

}

extension ListViewController: ListDisplayLogic {

    func show(_ viewModel: List.ViewModel) {
        self.viewModel = viewModel
    }

}
