//
//  ListPresenter.swift
//  Swiftmazing
//
//  Created by Hélio Mesquita on 14/12/19.
//  Copyright (c) 2019 Hélio Mesquita. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
// This tag below is used to create the testable files from the Cuckoo pod
// CUCKOO_TESTABLE

import UIKit

protocol ListPresentationLogic {
    func presentTitle(_ title: String)
    func reloadMap(_ repositories: [Repository])
    func nextPageMap(_ repositories: [Repository])
    func presentDetail()
    func presentTryAgain(message: String)
}

class ListPresenter: ListPresentationLogic {

    weak var viewController: ListDisplayLogic?

    func reloadMap(_ repositories: [Repository]) {
        let items = List.MapRepoViewModel(repositories: repositories).items
        viewController?.showReload(with: items)
    }

    func nextPageMap(_ repositories: [Repository]) {
        let items = List.MapRepoViewModel(repositories: repositories).items
        viewController?.showNextPage(with: items)
    }

    func presentTitle(_ title: String) {
        viewController?.showTitle(title)
    }

    func presentDetail() {
        viewController?.showDetail()
    }

    func presentTryAgain(message: String) {
        viewController?.showTryAgain(title: Text.anErrorHappened.value, message: message)
    }

}
