//
//  MainWorker.swift
//  Swiftmazing
//
//  Created by Hélio Mesquita on 14/12/19.
//  Copyright (c) 2019 Hélio Mesquita. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
// This tag below is used to create the testable files from the Cuckoo pod
// CUCKOO_TESTABLE

import Foundation
import PromiseKit
import Infrastructure

class MainWorker {

    let serviceProvider: ServiceProviderProtocol

    init(serviceProvider: ServiceProviderProtocol = ServiceProvider()) {
        self.serviceProvider = serviceProvider
    }

    var getTopRepositories: Promise<Main.Response> {
        let provider = PreviewTopRepositoriesProvider()
        return serviceProvider.execute(request: provider, parser: Main.Response.self)
    }

    var getMostRecentepositories: Promise<Main.Response> {
        let provider = PreviewMostRecentRepositoriesProvider()
        return serviceProvider.execute(request: provider, parser: Main.Response.self)
    }

}
