//
//  RepositoriesResponseTests.swift
//  Swiftmazing
//
//  Created by Hélio Mesquita on 26/05/25.
//

import Combine
import Foundation
import XCTest

@testable import Swiftmazing

class RepositoriesResponseTests: XCTestCase {

  func testDeconding() {
    let serviceProvider = ServiceProvider()
    let repositoriesResponse = try! serviceProvider.jsonDecoder.decode(RepositoriesResponse.self, from: jsonResponse)
    XCTAssertEqual(repositoriesResponse.items.count, 10)
  }

  func testListModels() {
    let serviceProvider = ServiceProvider()
    let repositoriesResponse = try! serviceProvider.jsonDecoder.decode(RepositoriesResponse.self, from: jsonResponse)
    let builder = RepositoryBuilder()
    let repositoriesModel = try! builder.build(response: repositoriesResponse)
    let repo = ListMapRepoViewModel(repositories: repositoriesModel.items)
    XCTAssertEqual(repo.items.count, 10)
  }

  let jsonResponse = """
  {
    "total_count": 1443243,
    "incomplete_results": false,
    "items": [
      {
        "id": 853402951,
        "node_id": "R_kgDOMt3lRw",
        "name": "inline",
        "full_name": "inline-chat/inline",
        "private": false,
        "owner": {
          "login": "inline-chat",
          "id": 180324040,
          "node_id": "O_kgDOCr-GyA",
          "avatar_url": "https://avatars.githubusercontent.com/u/180324040?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/inline-chat",
          "html_url": "https://github.com/inline-chat",
          "followers_url": "https://api.github.com/users/inline-chat/followers",
          "following_url": "https://api.github.com/users/inline-chat/following{/other_user}",
          "gists_url": "https://api.github.com/users/inline-chat/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/inline-chat/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/inline-chat/subscriptions",
          "organizations_url": "https://api.github.com/users/inline-chat/orgs",
          "repos_url": "https://api.github.com/users/inline-chat/repos",
          "events_url": "https://api.github.com/users/inline-chat/events{/privacy}",
          "received_events_url": "https://api.github.com/users/inline-chat/received_events",
          "type": "Organization",
          "user_view_type": "public",
          "site_admin": false
        },
        "html_url": "https://github.com/inline-chat/inline",
        "description": "💬 A better way to chat for teams",
        "fork": false,
        "url": "https://api.github.com/repos/inline-chat/inline",
        "forks_url": "https://api.github.com/repos/inline-chat/inline/forks",
        "keys_url": "https://api.github.com/repos/inline-chat/inline/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/inline-chat/inline/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/inline-chat/inline/teams",
        "hooks_url": "https://api.github.com/repos/inline-chat/inline/hooks",
        "issue_events_url": "https://api.github.com/repos/inline-chat/inline/issues/events{/number}",
        "events_url": "https://api.github.com/repos/inline-chat/inline/events",
        "assignees_url": "https://api.github.com/repos/inline-chat/inline/assignees{/user}",
        "branches_url": "https://api.github.com/repos/inline-chat/inline/branches{/branch}",
        "tags_url": "https://api.github.com/repos/inline-chat/inline/tags",
        "blobs_url": "https://api.github.com/repos/inline-chat/inline/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/inline-chat/inline/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/inline-chat/inline/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/inline-chat/inline/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/inline-chat/inline/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/inline-chat/inline/languages",
        "stargazers_url": "https://api.github.com/repos/inline-chat/inline/stargazers",
        "contributors_url": "https://api.github.com/repos/inline-chat/inline/contributors",
        "subscribers_url": "https://api.github.com/repos/inline-chat/inline/subscribers",
        "subscription_url": "https://api.github.com/repos/inline-chat/inline/subscription",
        "commits_url": "https://api.github.com/repos/inline-chat/inline/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/inline-chat/inline/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/inline-chat/inline/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/inline-chat/inline/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/inline-chat/inline/contents/{+path}",
        "compare_url": "https://api.github.com/repos/inline-chat/inline/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/inline-chat/inline/merges",
        "archive_url": "https://api.github.com/repos/inline-chat/inline/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/inline-chat/inline/downloads",
        "issues_url": "https://api.github.com/repos/inline-chat/inline/issues{/number}",
        "pulls_url": "https://api.github.com/repos/inline-chat/inline/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/inline-chat/inline/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/inline-chat/inline/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/inline-chat/inline/labels{/name}",
        "releases_url": "https://api.github.com/repos/inline-chat/inline/releases{/id}",
        "deployments_url": "https://api.github.com/repos/inline-chat/inline/deployments",
        "created_at": "2024-09-06T15:30:05Z",
        "updated_at": "2025-05-26T23:04:26Z",
        "pushed_at": "2025-05-26T23:04:23Z",
        "git_url": "git://github.com/inline-chat/inline.git",
        "ssh_url": "git@github.com:inline-chat/inline.git",
        "clone_url": "https://github.com/inline-chat/inline.git",
        "svn_url": "https://github.com/inline-chat/inline",
        "homepage": "https://inline.chat",
        "size": 31372,
        "stargazers_count": 568,
        "watchers_count": 568,
        "language": "Swift",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": false,
        "has_pages": false,
        "has_discussions": true,
        "forks_count": 21,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 0,
        "license": {
          "key": "agpl-3.0",
          "name": "GNU Affero General Public License v3.0",
          "spdx_id": "AGPL-3.0",
          "url": "https://api.github.com/licenses/agpl-3.0",
          "node_id": "MDc6TGljZW5zZTE="
        },
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [

        ],
        "visibility": "public",
        "forks": 21,
        "open_issues": 0,
        "watchers": 568,
        "default_branch": "main",
        "score": 1.0
      },
      {
        "id": 925970271,
        "node_id": "R_kgDONzEvXw",
        "name": "Bhagavad-Gita-Verses-iOS-App",
        "full_name": "MonkeyBonez/Bhagavad-Gita-Verses-iOS-App",
        "private": false,
        "owner": {
          "login": "MonkeyBonez",
          "id": 21704642,
          "node_id": "MDQ6VXNlcjIxNzA0NjQy",
          "avatar_url": "https://avatars.githubusercontent.com/u/21704642?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/MonkeyBonez",
          "html_url": "https://github.com/MonkeyBonez",
          "followers_url": "https://api.github.com/users/MonkeyBonez/followers",
          "following_url": "https://api.github.com/users/MonkeyBonez/following{/other_user}",
          "gists_url": "https://api.github.com/users/MonkeyBonez/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/MonkeyBonez/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/MonkeyBonez/subscriptions",
          "organizations_url": "https://api.github.com/users/MonkeyBonez/orgs",
          "repos_url": "https://api.github.com/users/MonkeyBonez/repos",
          "events_url": "https://api.github.com/users/MonkeyBonez/events{/privacy}",
          "received_events_url": "https://api.github.com/users/MonkeyBonez/received_events",
          "type": "User",
          "user_view_type": "public",
          "site_admin": false
        },
        "html_url": "https://github.com/MonkeyBonez/Bhagavad-Gita-Verses-iOS-App",
        "description": "A little passion project :)",
        "fork": false,
        "url": "https://api.github.com/repos/MonkeyBonez/Bhagavad-Gita-Verses-iOS-App",
        "forks_url": "https://api.github.com/repos/MonkeyBonez/Bhagavad-Gita-Verses-iOS-App/forks",
        "keys_url": "https://api.github.com/repos/MonkeyBonez/Bhagavad-Gita-Verses-iOS-App/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/MonkeyBonez/Bhagavad-Gita-Verses-iOS-App/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/MonkeyBonez/Bhagavad-Gita-Verses-iOS-App/teams",
        "hooks_url": "https://api.github.com/repos/MonkeyBonez/Bhagavad-Gita-Verses-iOS-App/hooks",
        "issue_events_url": "https://api.github.com/repos/MonkeyBonez/Bhagavad-Gita-Verses-iOS-App/issues/events{/number}",
        "events_url": "https://api.github.com/repos/MonkeyBonez/Bhagavad-Gita-Verses-iOS-App/events",
        "assignees_url": "https://api.github.com/repos/MonkeyBonez/Bhagavad-Gita-Verses-iOS-App/assignees{/user}",
        "branches_url": "https://api.github.com/repos/MonkeyBonez/Bhagavad-Gita-Verses-iOS-App/branches{/branch}",
        "tags_url": "https://api.github.com/repos/MonkeyBonez/Bhagavad-Gita-Verses-iOS-App/tags",
        "blobs_url": "https://api.github.com/repos/MonkeyBonez/Bhagavad-Gita-Verses-iOS-App/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/MonkeyBonez/Bhagavad-Gita-Verses-iOS-App/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/MonkeyBonez/Bhagavad-Gita-Verses-iOS-App/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/MonkeyBonez/Bhagavad-Gita-Verses-iOS-App/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/MonkeyBonez/Bhagavad-Gita-Verses-iOS-App/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/MonkeyBonez/Bhagavad-Gita-Verses-iOS-App/languages",
        "stargazers_url": "https://api.github.com/repos/MonkeyBonez/Bhagavad-Gita-Verses-iOS-App/stargazers",
        "contributors_url": "https://api.github.com/repos/MonkeyBonez/Bhagavad-Gita-Verses-iOS-App/contributors",
        "subscribers_url": "https://api.github.com/repos/MonkeyBonez/Bhagavad-Gita-Verses-iOS-App/subscribers",
        "subscription_url": "https://api.github.com/repos/MonkeyBonez/Bhagavad-Gita-Verses-iOS-App/subscription",
        "commits_url": "https://api.github.com/repos/MonkeyBonez/Bhagavad-Gita-Verses-iOS-App/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/MonkeyBonez/Bhagavad-Gita-Verses-iOS-App/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/MonkeyBonez/Bhagavad-Gita-Verses-iOS-App/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/MonkeyBonez/Bhagavad-Gita-Verses-iOS-App/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/MonkeyBonez/Bhagavad-Gita-Verses-iOS-App/contents/{+path}",
        "compare_url": "https://api.github.com/repos/MonkeyBonez/Bhagavad-Gita-Verses-iOS-App/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/MonkeyBonez/Bhagavad-Gita-Verses-iOS-App/merges",
        "archive_url": "https://api.github.com/repos/MonkeyBonez/Bhagavad-Gita-Verses-iOS-App/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/MonkeyBonez/Bhagavad-Gita-Verses-iOS-App/downloads",
        "issues_url": "https://api.github.com/repos/MonkeyBonez/Bhagavad-Gita-Verses-iOS-App/issues{/number}",
        "pulls_url": "https://api.github.com/repos/MonkeyBonez/Bhagavad-Gita-Verses-iOS-App/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/MonkeyBonez/Bhagavad-Gita-Verses-iOS-App/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/MonkeyBonez/Bhagavad-Gita-Verses-iOS-App/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/MonkeyBonez/Bhagavad-Gita-Verses-iOS-App/labels{/name}",
        "releases_url": "https://api.github.com/repos/MonkeyBonez/Bhagavad-Gita-Verses-iOS-App/releases{/id}",
        "deployments_url": "https://api.github.com/repos/MonkeyBonez/Bhagavad-Gita-Verses-iOS-App/deployments",
        "created_at": "2025-02-02T07:53:23Z",
        "updated_at": "2025-05-26T23:04:26Z",
        "pushed_at": "2025-05-26T23:04:22Z",
        "git_url": "git://github.com/MonkeyBonez/Bhagavad-Gita-Verses-iOS-App.git",
        "ssh_url": "git@github.com:MonkeyBonez/Bhagavad-Gita-Verses-iOS-App.git",
        "clone_url": "https://github.com/MonkeyBonez/Bhagavad-Gita-Verses-iOS-App.git",
        "svn_url": "https://github.com/MonkeyBonez/Bhagavad-Gita-Verses-iOS-App",
        "homepage": null,
        "size": 471,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": "Swift",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 0,
        "license": null,
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [

        ],
        "visibility": "public",
        "forks": 0,
        "open_issues": 0,
        "watchers": 0,
        "default_branch": "main",
        "score": 1.0
      },
      {
        "id": 989659569,
        "node_id": "R_kgDOOv0BsQ",
        "name": "Sentry",
        "full_name": "Fyannn09/Sentry",
        "private": false,
        "owner": {
          "login": "Fyannn09",
          "id": 157440439,
          "node_id": "U_kgDOCWJZtw",
          "avatar_url": "https://avatars.githubusercontent.com/u/157440439?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/Fyannn09",
          "html_url": "https://github.com/Fyannn09",
          "followers_url": "https://api.github.com/users/Fyannn09/followers",
          "following_url": "https://api.github.com/users/Fyannn09/following{/other_user}",
          "gists_url": "https://api.github.com/users/Fyannn09/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/Fyannn09/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/Fyannn09/subscriptions",
          "organizations_url": "https://api.github.com/users/Fyannn09/orgs",
          "repos_url": "https://api.github.com/users/Fyannn09/repos",
          "events_url": "https://api.github.com/users/Fyannn09/events{/privacy}",
          "received_events_url": "https://api.github.com/users/Fyannn09/received_events",
          "type": "User",
          "user_view_type": "public",
          "site_admin": false
        },
        "html_url": "https://github.com/Fyannn09/Sentry",
        "description": "# SentryA powerful macOS security monitoring application that detects unauthorized access attempts and records video evidence for you. With Sentry, you can confidently step away from your laptop, knowing it will alert you to any suspicious activity. 👨💻🔒",
        "fork": false,
        "url": "https://api.github.com/repos/Fyannn09/Sentry",
        "forks_url": "https://api.github.com/repos/Fyannn09/Sentry/forks",
        "keys_url": "https://api.github.com/repos/Fyannn09/Sentry/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/Fyannn09/Sentry/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/Fyannn09/Sentry/teams",
        "hooks_url": "https://api.github.com/repos/Fyannn09/Sentry/hooks",
        "issue_events_url": "https://api.github.com/repos/Fyannn09/Sentry/issues/events{/number}",
        "events_url": "https://api.github.com/repos/Fyannn09/Sentry/events",
        "assignees_url": "https://api.github.com/repos/Fyannn09/Sentry/assignees{/user}",
        "branches_url": "https://api.github.com/repos/Fyannn09/Sentry/branches{/branch}",
        "tags_url": "https://api.github.com/repos/Fyannn09/Sentry/tags",
        "blobs_url": "https://api.github.com/repos/Fyannn09/Sentry/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/Fyannn09/Sentry/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/Fyannn09/Sentry/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/Fyannn09/Sentry/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/Fyannn09/Sentry/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/Fyannn09/Sentry/languages",
        "stargazers_url": "https://api.github.com/repos/Fyannn09/Sentry/stargazers",
        "contributors_url": "https://api.github.com/repos/Fyannn09/Sentry/contributors",
        "subscribers_url": "https://api.github.com/repos/Fyannn09/Sentry/subscribers",
        "subscription_url": "https://api.github.com/repos/Fyannn09/Sentry/subscription",
        "commits_url": "https://api.github.com/repos/Fyannn09/Sentry/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/Fyannn09/Sentry/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/Fyannn09/Sentry/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/Fyannn09/Sentry/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/Fyannn09/Sentry/contents/{+path}",
        "compare_url": "https://api.github.com/repos/Fyannn09/Sentry/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/Fyannn09/Sentry/merges",
        "archive_url": "https://api.github.com/repos/Fyannn09/Sentry/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/Fyannn09/Sentry/downloads",
        "issues_url": "https://api.github.com/repos/Fyannn09/Sentry/issues{/number}",
        "pulls_url": "https://api.github.com/repos/Fyannn09/Sentry/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/Fyannn09/Sentry/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/Fyannn09/Sentry/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/Fyannn09/Sentry/labels{/name}",
        "releases_url": "https://api.github.com/repos/Fyannn09/Sentry/releases{/id}",
        "deployments_url": "https://api.github.com/repos/Fyannn09/Sentry/deployments",
        "created_at": "2025-05-24T15:00:57Z",
        "updated_at": "2025-05-26T23:04:20Z",
        "pushed_at": "2025-05-26T23:04:17Z",
        "git_url": "git://github.com/Fyannn09/Sentry.git",
        "ssh_url": "git@github.com:Fyannn09/Sentry.git",
        "clone_url": "https://github.com/Fyannn09/Sentry.git",
        "svn_url": "https://github.com/Fyannn09/Sentry",
        "homepage": null,
        "size": 2080,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": "Swift",
        "has_issues": false,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 0,
        "license": {
          "key": "mit",
          "name": "MIT License",
          "spdx_id": "MIT",
          "url": "https://api.github.com/licenses/mit",
          "node_id": "MDc6TGljZW5zZTEz"
        },
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [
          "crash-reporting",
          "crash-reports",
          "csp-report",
          "django",
          "documentation",
          "fair-source",
          "go",
          "hacktoberfest",
          "ios",
          "monitoring",
          "php",
          "sdk",
          "security",
          "sentry-client",
          "tag-archived",
          "team-web-backend",
          "typescript",
          "vue"
        ],
        "visibility": "public",
        "forks": 0,
        "open_issues": 0,
        "watchers": 0,
        "default_branch": "main",
        "score": 1.0
      },
      {
        "id": 989640353,
        "node_id": "R_kgDOOvy2oQ",
        "name": "SkyLightWindow",
        "full_name": "usman1234farooq/SkyLightWindow",
        "private": false,
        "owner": {
          "login": "usman1234farooq",
          "id": 209232381,
          "node_id": "U_kgDODHih_Q",
          "avatar_url": "https://avatars.githubusercontent.com/u/209232381?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/usman1234farooq",
          "html_url": "https://github.com/usman1234farooq",
          "followers_url": "https://api.github.com/users/usman1234farooq/followers",
          "following_url": "https://api.github.com/users/usman1234farooq/following{/other_user}",
          "gists_url": "https://api.github.com/users/usman1234farooq/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/usman1234farooq/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/usman1234farooq/subscriptions",
          "organizations_url": "https://api.github.com/users/usman1234farooq/orgs",
          "repos_url": "https://api.github.com/users/usman1234farooq/repos",
          "events_url": "https://api.github.com/users/usman1234farooq/events{/privacy}",
          "received_events_url": "https://api.github.com/users/usman1234farooq/received_events",
          "type": "User",
          "user_view_type": "public",
          "site_admin": false
        },
        "html_url": "https://github.com/usman1234farooq/SkyLightWindow",
        "description": null,
        "fork": false,
        "url": "https://api.github.com/repos/usman1234farooq/SkyLightWindow",
        "forks_url": "https://api.github.com/repos/usman1234farooq/SkyLightWindow/forks",
        "keys_url": "https://api.github.com/repos/usman1234farooq/SkyLightWindow/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/usman1234farooq/SkyLightWindow/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/usman1234farooq/SkyLightWindow/teams",
        "hooks_url": "https://api.github.com/repos/usman1234farooq/SkyLightWindow/hooks",
        "issue_events_url": "https://api.github.com/repos/usman1234farooq/SkyLightWindow/issues/events{/number}",
        "events_url": "https://api.github.com/repos/usman1234farooq/SkyLightWindow/events",
        "assignees_url": "https://api.github.com/repos/usman1234farooq/SkyLightWindow/assignees{/user}",
        "branches_url": "https://api.github.com/repos/usman1234farooq/SkyLightWindow/branches{/branch}",
        "tags_url": "https://api.github.com/repos/usman1234farooq/SkyLightWindow/tags",
        "blobs_url": "https://api.github.com/repos/usman1234farooq/SkyLightWindow/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/usman1234farooq/SkyLightWindow/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/usman1234farooq/SkyLightWindow/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/usman1234farooq/SkyLightWindow/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/usman1234farooq/SkyLightWindow/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/usman1234farooq/SkyLightWindow/languages",
        "stargazers_url": "https://api.github.com/repos/usman1234farooq/SkyLightWindow/stargazers",
        "contributors_url": "https://api.github.com/repos/usman1234farooq/SkyLightWindow/contributors",
        "subscribers_url": "https://api.github.com/repos/usman1234farooq/SkyLightWindow/subscribers",
        "subscription_url": "https://api.github.com/repos/usman1234farooq/SkyLightWindow/subscription",
        "commits_url": "https://api.github.com/repos/usman1234farooq/SkyLightWindow/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/usman1234farooq/SkyLightWindow/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/usman1234farooq/SkyLightWindow/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/usman1234farooq/SkyLightWindow/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/usman1234farooq/SkyLightWindow/contents/{+path}",
        "compare_url": "https://api.github.com/repos/usman1234farooq/SkyLightWindow/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/usman1234farooq/SkyLightWindow/merges",
        "archive_url": "https://api.github.com/repos/usman1234farooq/SkyLightWindow/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/usman1234farooq/SkyLightWindow/downloads",
        "issues_url": "https://api.github.com/repos/usman1234farooq/SkyLightWindow/issues{/number}",
        "pulls_url": "https://api.github.com/repos/usman1234farooq/SkyLightWindow/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/usman1234farooq/SkyLightWindow/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/usman1234farooq/SkyLightWindow/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/usman1234farooq/SkyLightWindow/labels{/name}",
        "releases_url": "https://api.github.com/repos/usman1234farooq/SkyLightWindow/releases{/id}",
        "deployments_url": "https://api.github.com/repos/usman1234farooq/SkyLightWindow/deployments",
        "created_at": "2025-05-24T14:16:26Z",
        "updated_at": "2025-05-26T23:04:11Z",
        "pushed_at": "2025-05-26T23:04:08Z",
        "git_url": "git://github.com/usman1234farooq/SkyLightWindow.git",
        "ssh_url": "git@github.com:usman1234farooq/SkyLightWindow.git",
        "clone_url": "https://github.com/usman1234farooq/SkyLightWindow.git",
        "svn_url": "https://github.com/usman1234farooq/SkyLightWindow",
        "homepage": null,
        "size": 5434,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": "Swift",
        "has_issues": false,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 0,
        "license": {
          "key": "mit",
          "name": "MIT License",
          "spdx_id": "MIT",
          "url": "https://api.github.com/licenses/mit",
          "node_id": "MDc6TGljZW5zZTEz"
        },
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [

        ],
        "visibility": "public",
        "forks": 0,
        "open_issues": 0,
        "watchers": 0,
        "default_branch": "main",
        "score": 1.0
      },
      {
        "id": 989883408,
        "node_id": "R_kgDOOwBsEA",
        "name": "CharityPad",
        "full_name": "Zrodkin/CharityPad",
        "private": false,
        "owner": {
          "login": "Zrodkin",
          "id": 206629468,
          "node_id": "U_kgDODFDqXA",
          "avatar_url": "https://avatars.githubusercontent.com/u/206629468?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/Zrodkin",
          "html_url": "https://github.com/Zrodkin",
          "followers_url": "https://api.github.com/users/Zrodkin/followers",
          "following_url": "https://api.github.com/users/Zrodkin/following{/other_user}",
          "gists_url": "https://api.github.com/users/Zrodkin/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/Zrodkin/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/Zrodkin/subscriptions",
          "organizations_url": "https://api.github.com/users/Zrodkin/orgs",
          "repos_url": "https://api.github.com/users/Zrodkin/repos",
          "events_url": "https://api.github.com/users/Zrodkin/events{/privacy}",
          "received_events_url": "https://api.github.com/users/Zrodkin/received_events",
          "type": "User",
          "user_view_type": "public",
          "site_admin": false
        },
        "html_url": "https://github.com/Zrodkin/CharityPad",
        "description": null,
        "fork": false,
        "url": "https://api.github.com/repos/Zrodkin/CharityPad",
        "forks_url": "https://api.github.com/repos/Zrodkin/CharityPad/forks",
        "keys_url": "https://api.github.com/repos/Zrodkin/CharityPad/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/Zrodkin/CharityPad/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/Zrodkin/CharityPad/teams",
        "hooks_url": "https://api.github.com/repos/Zrodkin/CharityPad/hooks",
        "issue_events_url": "https://api.github.com/repos/Zrodkin/CharityPad/issues/events{/number}",
        "events_url": "https://api.github.com/repos/Zrodkin/CharityPad/events",
        "assignees_url": "https://api.github.com/repos/Zrodkin/CharityPad/assignees{/user}",
        "branches_url": "https://api.github.com/repos/Zrodkin/CharityPad/branches{/branch}",
        "tags_url": "https://api.github.com/repos/Zrodkin/CharityPad/tags",
        "blobs_url": "https://api.github.com/repos/Zrodkin/CharityPad/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/Zrodkin/CharityPad/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/Zrodkin/CharityPad/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/Zrodkin/CharityPad/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/Zrodkin/CharityPad/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/Zrodkin/CharityPad/languages",
        "stargazers_url": "https://api.github.com/repos/Zrodkin/CharityPad/stargazers",
        "contributors_url": "https://api.github.com/repos/Zrodkin/CharityPad/contributors",
        "subscribers_url": "https://api.github.com/repos/Zrodkin/CharityPad/subscribers",
        "subscription_url": "https://api.github.com/repos/Zrodkin/CharityPad/subscription",
        "commits_url": "https://api.github.com/repos/Zrodkin/CharityPad/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/Zrodkin/CharityPad/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/Zrodkin/CharityPad/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/Zrodkin/CharityPad/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/Zrodkin/CharityPad/contents/{+path}",
        "compare_url": "https://api.github.com/repos/Zrodkin/CharityPad/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/Zrodkin/CharityPad/merges",
        "archive_url": "https://api.github.com/repos/Zrodkin/CharityPad/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/Zrodkin/CharityPad/downloads",
        "issues_url": "https://api.github.com/repos/Zrodkin/CharityPad/issues{/number}",
        "pulls_url": "https://api.github.com/repos/Zrodkin/CharityPad/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/Zrodkin/CharityPad/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/Zrodkin/CharityPad/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/Zrodkin/CharityPad/labels{/name}",
        "releases_url": "https://api.github.com/repos/Zrodkin/CharityPad/releases{/id}",
        "deployments_url": "https://api.github.com/repos/Zrodkin/CharityPad/deployments",
        "created_at": "2025-05-25T03:17:50Z",
        "updated_at": "2025-05-26T23:03:48Z",
        "pushed_at": "2025-05-26T23:03:45Z",
        "git_url": "git://github.com/Zrodkin/CharityPad.git",
        "ssh_url": "git@github.com:Zrodkin/CharityPad.git",
        "clone_url": "https://github.com/Zrodkin/CharityPad.git",
        "svn_url": "https://github.com/Zrodkin/CharityPad",
        "homepage": null,
        "size": 1284,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": "Swift",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 0,
        "license": null,
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [

        ],
        "visibility": "public",
        "forks": 0,
        "open_issues": 0,
        "watchers": 0,
        "default_branch": "main",
        "score": 1.0
      },
      {
        "id": 986307321,
        "node_id": "R_kgDOOsna-Q",
        "name": "CodingPractice",
        "full_name": "narendraiosd7/CodingPractice",
        "private": false,
        "owner": {
          "login": "narendraiosd7",
          "id": 53249051,
          "node_id": "MDQ6VXNlcjUzMjQ5MDUx",
          "avatar_url": "https://avatars.githubusercontent.com/u/53249051?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/narendraiosd7",
          "html_url": "https://github.com/narendraiosd7",
          "followers_url": "https://api.github.com/users/narendraiosd7/followers",
          "following_url": "https://api.github.com/users/narendraiosd7/following{/other_user}",
          "gists_url": "https://api.github.com/users/narendraiosd7/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/narendraiosd7/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/narendraiosd7/subscriptions",
          "organizations_url": "https://api.github.com/users/narendraiosd7/orgs",
          "repos_url": "https://api.github.com/users/narendraiosd7/repos",
          "events_url": "https://api.github.com/users/narendraiosd7/events{/privacy}",
          "received_events_url": "https://api.github.com/users/narendraiosd7/received_events",
          "type": "User",
          "user_view_type": "public",
          "site_admin": false
        },
        "html_url": "https://github.com/narendraiosd7/CodingPractice",
        "description": "DSA Practice",
        "fork": false,
        "url": "https://api.github.com/repos/narendraiosd7/CodingPractice",
        "forks_url": "https://api.github.com/repos/narendraiosd7/CodingPractice/forks",
        "keys_url": "https://api.github.com/repos/narendraiosd7/CodingPractice/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/narendraiosd7/CodingPractice/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/narendraiosd7/CodingPractice/teams",
        "hooks_url": "https://api.github.com/repos/narendraiosd7/CodingPractice/hooks",
        "issue_events_url": "https://api.github.com/repos/narendraiosd7/CodingPractice/issues/events{/number}",
        "events_url": "https://api.github.com/repos/narendraiosd7/CodingPractice/events",
        "assignees_url": "https://api.github.com/repos/narendraiosd7/CodingPractice/assignees{/user}",
        "branches_url": "https://api.github.com/repos/narendraiosd7/CodingPractice/branches{/branch}",
        "tags_url": "https://api.github.com/repos/narendraiosd7/CodingPractice/tags",
        "blobs_url": "https://api.github.com/repos/narendraiosd7/CodingPractice/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/narendraiosd7/CodingPractice/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/narendraiosd7/CodingPractice/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/narendraiosd7/CodingPractice/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/narendraiosd7/CodingPractice/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/narendraiosd7/CodingPractice/languages",
        "stargazers_url": "https://api.github.com/repos/narendraiosd7/CodingPractice/stargazers",
        "contributors_url": "https://api.github.com/repos/narendraiosd7/CodingPractice/contributors",
        "subscribers_url": "https://api.github.com/repos/narendraiosd7/CodingPractice/subscribers",
        "subscription_url": "https://api.github.com/repos/narendraiosd7/CodingPractice/subscription",
        "commits_url": "https://api.github.com/repos/narendraiosd7/CodingPractice/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/narendraiosd7/CodingPractice/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/narendraiosd7/CodingPractice/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/narendraiosd7/CodingPractice/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/narendraiosd7/CodingPractice/contents/{+path}",
        "compare_url": "https://api.github.com/repos/narendraiosd7/CodingPractice/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/narendraiosd7/CodingPractice/merges",
        "archive_url": "https://api.github.com/repos/narendraiosd7/CodingPractice/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/narendraiosd7/CodingPractice/downloads",
        "issues_url": "https://api.github.com/repos/narendraiosd7/CodingPractice/issues{/number}",
        "pulls_url": "https://api.github.com/repos/narendraiosd7/CodingPractice/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/narendraiosd7/CodingPractice/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/narendraiosd7/CodingPractice/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/narendraiosd7/CodingPractice/labels{/name}",
        "releases_url": "https://api.github.com/repos/narendraiosd7/CodingPractice/releases{/id}",
        "deployments_url": "https://api.github.com/repos/narendraiosd7/CodingPractice/deployments",
        "created_at": "2025-05-19T12:15:51Z",
        "updated_at": "2025-05-26T23:03:43Z",
        "pushed_at": "2025-05-26T23:03:40Z",
        "git_url": "git://github.com/narendraiosd7/CodingPractice.git",
        "ssh_url": "git@github.com:narendraiosd7/CodingPractice.git",
        "clone_url": "https://github.com/narendraiosd7/CodingPractice.git",
        "svn_url": "https://github.com/narendraiosd7/CodingPractice",
        "homepage": null,
        "size": 17,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": "Swift",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 0,
        "license": {
          "key": "mit",
          "name": "MIT License",
          "spdx_id": "MIT",
          "url": "https://api.github.com/licenses/mit",
          "node_id": "MDc6TGljZW5zZTEz"
        },
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [

        ],
        "visibility": "public",
        "forks": 0,
        "open_issues": 0,
        "watchers": 0,
        "default_branch": "main",
        "score": 1.0
      },
      {
        "id": 964897177,
        "node_id": "R_kgDOOYMpmQ",
        "name": "Finwise",
        "full_name": "goksualc/Finwise",
        "private": false,
        "owner": {
          "login": "goksualc",
          "id": 71547915,
          "node_id": "MDQ6VXNlcjcxNTQ3OTE1",
          "avatar_url": "https://avatars.githubusercontent.com/u/71547915?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/goksualc",
          "html_url": "https://github.com/goksualc",
          "followers_url": "https://api.github.com/users/goksualc/followers",
          "following_url": "https://api.github.com/users/goksualc/following{/other_user}",
          "gists_url": "https://api.github.com/users/goksualc/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/goksualc/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/goksualc/subscriptions",
          "organizations_url": "https://api.github.com/users/goksualc/orgs",
          "repos_url": "https://api.github.com/users/goksualc/repos",
          "events_url": "https://api.github.com/users/goksualc/events{/privacy}",
          "received_events_url": "https://api.github.com/users/goksualc/received_events",
          "type": "User",
          "user_view_type": "public",
          "site_admin": false
        },
        "html_url": "https://github.com/goksualc/Finwise",
        "description": null,
        "fork": false,
        "url": "https://api.github.com/repos/goksualc/Finwise",
        "forks_url": "https://api.github.com/repos/goksualc/Finwise/forks",
        "keys_url": "https://api.github.com/repos/goksualc/Finwise/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/goksualc/Finwise/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/goksualc/Finwise/teams",
        "hooks_url": "https://api.github.com/repos/goksualc/Finwise/hooks",
        "issue_events_url": "https://api.github.com/repos/goksualc/Finwise/issues/events{/number}",
        "events_url": "https://api.github.com/repos/goksualc/Finwise/events",
        "assignees_url": "https://api.github.com/repos/goksualc/Finwise/assignees{/user}",
        "branches_url": "https://api.github.com/repos/goksualc/Finwise/branches{/branch}",
        "tags_url": "https://api.github.com/repos/goksualc/Finwise/tags",
        "blobs_url": "https://api.github.com/repos/goksualc/Finwise/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/goksualc/Finwise/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/goksualc/Finwise/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/goksualc/Finwise/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/goksualc/Finwise/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/goksualc/Finwise/languages",
        "stargazers_url": "https://api.github.com/repos/goksualc/Finwise/stargazers",
        "contributors_url": "https://api.github.com/repos/goksualc/Finwise/contributors",
        "subscribers_url": "https://api.github.com/repos/goksualc/Finwise/subscribers",
        "subscription_url": "https://api.github.com/repos/goksualc/Finwise/subscription",
        "commits_url": "https://api.github.com/repos/goksualc/Finwise/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/goksualc/Finwise/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/goksualc/Finwise/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/goksualc/Finwise/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/goksualc/Finwise/contents/{+path}",
        "compare_url": "https://api.github.com/repos/goksualc/Finwise/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/goksualc/Finwise/merges",
        "archive_url": "https://api.github.com/repos/goksualc/Finwise/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/goksualc/Finwise/downloads",
        "issues_url": "https://api.github.com/repos/goksualc/Finwise/issues{/number}",
        "pulls_url": "https://api.github.com/repos/goksualc/Finwise/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/goksualc/Finwise/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/goksualc/Finwise/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/goksualc/Finwise/labels{/name}",
        "releases_url": "https://api.github.com/repos/goksualc/Finwise/releases{/id}",
        "deployments_url": "https://api.github.com/repos/goksualc/Finwise/deployments",
        "created_at": "2025-04-12T01:40:55Z",
        "updated_at": "2025-05-26T23:03:28Z",
        "pushed_at": "2025-05-26T23:03:25Z",
        "git_url": "git://github.com/goksualc/Finwise.git",
        "ssh_url": "git@github.com:goksualc/Finwise.git",
        "clone_url": "https://github.com/goksualc/Finwise.git",
        "svn_url": "https://github.com/goksualc/Finwise",
        "homepage": null,
        "size": 305,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": "Swift",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 0,
        "license": null,
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [

        ],
        "visibility": "public",
        "forks": 0,
        "open_issues": 0,
        "watchers": 0,
        "default_branch": "main",
        "score": 1.0
      },
      {
        "id": 667069221,
        "node_id": "R_kgDOJ8KrJQ",
        "name": "minip",
        "full_name": "Yosorable/minip",
        "private": false,
        "owner": {
          "login": "Yosorable",
          "id": 58335141,
          "node_id": "MDQ6VXNlcjU4MzM1MTQx",
          "avatar_url": "https://avatars.githubusercontent.com/u/58335141?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/Yosorable",
          "html_url": "https://github.com/Yosorable",
          "followers_url": "https://api.github.com/users/Yosorable/followers",
          "following_url": "https://api.github.com/users/Yosorable/following{/other_user}",
          "gists_url": "https://api.github.com/users/Yosorable/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/Yosorable/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/Yosorable/subscriptions",
          "organizations_url": "https://api.github.com/users/Yosorable/orgs",
          "repos_url": "https://api.github.com/users/Yosorable/repos",
          "events_url": "https://api.github.com/users/Yosorable/events{/privacy}",
          "received_events_url": "https://api.github.com/users/Yosorable/received_events",
          "type": "User",
          "user_view_type": "public",
          "site_admin": false
        },
        "html_url": "https://github.com/Yosorable/minip",
        "description": "Build native-like applications easily.",
        "fork": false,
        "url": "https://api.github.com/repos/Yosorable/minip",
        "forks_url": "https://api.github.com/repos/Yosorable/minip/forks",
        "keys_url": "https://api.github.com/repos/Yosorable/minip/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/Yosorable/minip/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/Yosorable/minip/teams",
        "hooks_url": "https://api.github.com/repos/Yosorable/minip/hooks",
        "issue_events_url": "https://api.github.com/repos/Yosorable/minip/issues/events{/number}",
        "events_url": "https://api.github.com/repos/Yosorable/minip/events",
        "assignees_url": "https://api.github.com/repos/Yosorable/minip/assignees{/user}",
        "branches_url": "https://api.github.com/repos/Yosorable/minip/branches{/branch}",
        "tags_url": "https://api.github.com/repos/Yosorable/minip/tags",
        "blobs_url": "https://api.github.com/repos/Yosorable/minip/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/Yosorable/minip/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/Yosorable/minip/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/Yosorable/minip/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/Yosorable/minip/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/Yosorable/minip/languages",
        "stargazers_url": "https://api.github.com/repos/Yosorable/minip/stargazers",
        "contributors_url": "https://api.github.com/repos/Yosorable/minip/contributors",
        "subscribers_url": "https://api.github.com/repos/Yosorable/minip/subscribers",
        "subscription_url": "https://api.github.com/repos/Yosorable/minip/subscription",
        "commits_url": "https://api.github.com/repos/Yosorable/minip/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/Yosorable/minip/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/Yosorable/minip/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/Yosorable/minip/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/Yosorable/minip/contents/{+path}",
        "compare_url": "https://api.github.com/repos/Yosorable/minip/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/Yosorable/minip/merges",
        "archive_url": "https://api.github.com/repos/Yosorable/minip/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/Yosorable/minip/downloads",
        "issues_url": "https://api.github.com/repos/Yosorable/minip/issues{/number}",
        "pulls_url": "https://api.github.com/repos/Yosorable/minip/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/Yosorable/minip/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/Yosorable/minip/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/Yosorable/minip/labels{/name}",
        "releases_url": "https://api.github.com/repos/Yosorable/minip/releases{/id}",
        "deployments_url": "https://api.github.com/repos/Yosorable/minip/deployments",
        "created_at": "2023-07-16T14:40:06Z",
        "updated_at": "2025-05-26T23:02:37Z",
        "pushed_at": "2025-05-26T23:02:34Z",
        "git_url": "git://github.com/Yosorable/minip.git",
        "ssh_url": "git@github.com:Yosorable/minip.git",
        "clone_url": "https://github.com/Yosorable/minip.git",
        "svn_url": "https://github.com/Yosorable/minip",
        "homepage": "https://minip.lzyl.win",
        "size": 15328,
        "stargazers_count": 2,
        "watchers_count": 2,
        "language": "Swift",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": false,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 0,
        "license": {
          "key": "mit",
          "name": "MIT License",
          "spdx_id": "MIT",
          "url": "https://api.github.com/licenses/mit",
          "node_id": "MDc6TGljZW5zZTEz"
        },
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [

        ],
        "visibility": "public",
        "forks": 0,
        "open_issues": 0,
        "watchers": 2,
        "default_branch": "main",
        "score": 1.0
      },
      {
        "id": 986080750,
        "node_id": "R_kgDOOsZl7g",
        "name": "Lunr",
        "full_name": "Lwin-Oo/Lunr",
        "private": false,
        "owner": {
          "login": "Lwin-Oo",
          "id": 78170253,
          "node_id": "MDQ6VXNlcjc4MTcwMjUz",
          "avatar_url": "https://avatars.githubusercontent.com/u/78170253?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/Lwin-Oo",
          "html_url": "https://github.com/Lwin-Oo",
          "followers_url": "https://api.github.com/users/Lwin-Oo/followers",
          "following_url": "https://api.github.com/users/Lwin-Oo/following{/other_user}",
          "gists_url": "https://api.github.com/users/Lwin-Oo/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/Lwin-Oo/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/Lwin-Oo/subscriptions",
          "organizations_url": "https://api.github.com/users/Lwin-Oo/orgs",
          "repos_url": "https://api.github.com/users/Lwin-Oo/repos",
          "events_url": "https://api.github.com/users/Lwin-Oo/events{/privacy}",
          "received_events_url": "https://api.github.com/users/Lwin-Oo/received_events",
          "type": "User",
          "user_view_type": "public",
          "site_admin": false
        },
        "html_url": "https://github.com/Lwin-Oo/Lunr",
        "description": "This is Mac App version of Lunr, the project from ProtocolParallel",
        "fork": false,
        "url": "https://api.github.com/repos/Lwin-Oo/Lunr",
        "forks_url": "https://api.github.com/repos/Lwin-Oo/Lunr/forks",
        "keys_url": "https://api.github.com/repos/Lwin-Oo/Lunr/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/Lwin-Oo/Lunr/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/Lwin-Oo/Lunr/teams",
        "hooks_url": "https://api.github.com/repos/Lwin-Oo/Lunr/hooks",
        "issue_events_url": "https://api.github.com/repos/Lwin-Oo/Lunr/issues/events{/number}",
        "events_url": "https://api.github.com/repos/Lwin-Oo/Lunr/events",
        "assignees_url": "https://api.github.com/repos/Lwin-Oo/Lunr/assignees{/user}",
        "branches_url": "https://api.github.com/repos/Lwin-Oo/Lunr/branches{/branch}",
        "tags_url": "https://api.github.com/repos/Lwin-Oo/Lunr/tags",
        "blobs_url": "https://api.github.com/repos/Lwin-Oo/Lunr/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/Lwin-Oo/Lunr/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/Lwin-Oo/Lunr/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/Lwin-Oo/Lunr/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/Lwin-Oo/Lunr/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/Lwin-Oo/Lunr/languages",
        "stargazers_url": "https://api.github.com/repos/Lwin-Oo/Lunr/stargazers",
        "contributors_url": "https://api.github.com/repos/Lwin-Oo/Lunr/contributors",
        "subscribers_url": "https://api.github.com/repos/Lwin-Oo/Lunr/subscribers",
        "subscription_url": "https://api.github.com/repos/Lwin-Oo/Lunr/subscription",
        "commits_url": "https://api.github.com/repos/Lwin-Oo/Lunr/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/Lwin-Oo/Lunr/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/Lwin-Oo/Lunr/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/Lwin-Oo/Lunr/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/Lwin-Oo/Lunr/contents/{+path}",
        "compare_url": "https://api.github.com/repos/Lwin-Oo/Lunr/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/Lwin-Oo/Lunr/merges",
        "archive_url": "https://api.github.com/repos/Lwin-Oo/Lunr/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/Lwin-Oo/Lunr/downloads",
        "issues_url": "https://api.github.com/repos/Lwin-Oo/Lunr/issues{/number}",
        "pulls_url": "https://api.github.com/repos/Lwin-Oo/Lunr/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/Lwin-Oo/Lunr/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/Lwin-Oo/Lunr/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/Lwin-Oo/Lunr/labels{/name}",
        "releases_url": "https://api.github.com/repos/Lwin-Oo/Lunr/releases{/id}",
        "deployments_url": "https://api.github.com/repos/Lwin-Oo/Lunr/deployments",
        "created_at": "2025-05-19T04:45:23Z",
        "updated_at": "2025-05-26T23:02:26Z",
        "pushed_at": "2025-05-26T23:02:22Z",
        "git_url": "git://github.com/Lwin-Oo/Lunr.git",
        "ssh_url": "git@github.com:Lwin-Oo/Lunr.git",
        "clone_url": "https://github.com/Lwin-Oo/Lunr.git",
        "svn_url": "https://github.com/Lwin-Oo/Lunr",
        "homepage": null,
        "size": 67,
        "stargazers_count": 1,
        "watchers_count": 1,
        "language": "Swift",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": false,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 0,
        "license": null,
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [

        ],
        "visibility": "public",
        "forks": 0,
        "open_issues": 0,
        "watchers": 1,
        "default_branch": "main",
        "score": 1.0
      },
      {
        "id": 988769046,
        "node_id": "R_kgDOOu9rFg",
        "name": "ListViewKit",
        "full_name": "Cafezinho0/ListViewKit",
        "private": false,
        "owner": {
          "login": "Cafezinho0",
          "id": 177094113,
          "node_id": "U_kgDOCo494Q",
          "avatar_url": "https://avatars.githubusercontent.com/u/177094113?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/Cafezinho0",
          "html_url": "https://github.com/Cafezinho0",
          "followers_url": "https://api.github.com/users/Cafezinho0/followers",
          "following_url": "https://api.github.com/users/Cafezinho0/following{/other_user}",
          "gists_url": "https://api.github.com/users/Cafezinho0/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/Cafezinho0/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/Cafezinho0/subscriptions",
          "organizations_url": "https://api.github.com/users/Cafezinho0/orgs",
          "repos_url": "https://api.github.com/users/Cafezinho0/repos",
          "events_url": "https://api.github.com/users/Cafezinho0/events{/privacy}",
          "received_events_url": "https://api.github.com/users/Cafezinho0/received_events",
          "type": "User",
          "user_view_type": "public",
          "site_admin": false
        },
        "html_url": "https://github.com/Cafezinho0/ListViewKit",
        "description": "ListViewKit offers a seamless UITableView alternative for Swift developers, ensuring smooth user experiences without glitches. Easily integrate it into your project with Swift Package Manager and enjoy live data updates and smooth scrolling. 🐙🌟",
        "fork": false,
        "url": "https://api.github.com/repos/Cafezinho0/ListViewKit",
        "forks_url": "https://api.github.com/repos/Cafezinho0/ListViewKit/forks",
        "keys_url": "https://api.github.com/repos/Cafezinho0/ListViewKit/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/Cafezinho0/ListViewKit/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/Cafezinho0/ListViewKit/teams",
        "hooks_url": "https://api.github.com/repos/Cafezinho0/ListViewKit/hooks",
        "issue_events_url": "https://api.github.com/repos/Cafezinho0/ListViewKit/issues/events{/number}",
        "events_url": "https://api.github.com/repos/Cafezinho0/ListViewKit/events",
        "assignees_url": "https://api.github.com/repos/Cafezinho0/ListViewKit/assignees{/user}",
        "branches_url": "https://api.github.com/repos/Cafezinho0/ListViewKit/branches{/branch}",
        "tags_url": "https://api.github.com/repos/Cafezinho0/ListViewKit/tags",
        "blobs_url": "https://api.github.com/repos/Cafezinho0/ListViewKit/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/Cafezinho0/ListViewKit/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/Cafezinho0/ListViewKit/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/Cafezinho0/ListViewKit/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/Cafezinho0/ListViewKit/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/Cafezinho0/ListViewKit/languages",
        "stargazers_url": "https://api.github.com/repos/Cafezinho0/ListViewKit/stargazers",
        "contributors_url": "https://api.github.com/repos/Cafezinho0/ListViewKit/contributors",
        "subscribers_url": "https://api.github.com/repos/Cafezinho0/ListViewKit/subscribers",
        "subscription_url": "https://api.github.com/repos/Cafezinho0/ListViewKit/subscription",
        "commits_url": "https://api.github.com/repos/Cafezinho0/ListViewKit/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/Cafezinho0/ListViewKit/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/Cafezinho0/ListViewKit/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/Cafezinho0/ListViewKit/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/Cafezinho0/ListViewKit/contents/{+path}",
        "compare_url": "https://api.github.com/repos/Cafezinho0/ListViewKit/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/Cafezinho0/ListViewKit/merges",
        "archive_url": "https://api.github.com/repos/Cafezinho0/ListViewKit/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/Cafezinho0/ListViewKit/downloads",
        "issues_url": "https://api.github.com/repos/Cafezinho0/ListViewKit/issues{/number}",
        "pulls_url": "https://api.github.com/repos/Cafezinho0/ListViewKit/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/Cafezinho0/ListViewKit/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/Cafezinho0/ListViewKit/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/Cafezinho0/ListViewKit/labels{/name}",
        "releases_url": "https://api.github.com/repos/Cafezinho0/ListViewKit/releases{/id}",
        "deployments_url": "https://api.github.com/repos/Cafezinho0/ListViewKit/deployments",
        "created_at": "2025-05-23T03:42:16Z",
        "updated_at": "2025-05-26T23:01:51Z",
        "pushed_at": "2025-05-26T23:01:48Z",
        "git_url": "git://github.com/Cafezinho0/ListViewKit.git",
        "ssh_url": "git@github.com:Cafezinho0/ListViewKit.git",
        "clone_url": "https://github.com/Cafezinho0/ListViewKit.git",
        "svn_url": "https://github.com/Cafezinho0/ListViewKit",
        "homepage": null,
        "size": 238,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": "Swift",
        "has_issues": false,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 0,
        "license": {
          "key": "mit",
          "name": "MIT License",
          "spdx_id": "MIT",
          "url": "https://api.github.com/licenses/mit",
          "node_id": "MDc6TGljZW5zZTEz"
        },
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [

        ],
        "visibility": "public",
        "forks": 0,
        "open_issues": 0,
        "watchers": 0,
        "default_branch": "main",
        "score": 1.0
      }
    ]
  }
  """.data(using: .utf8)!


}

