//
//  ListRouter.swift
//  Swiftmazing
//
//  Created by Hélio Mesquita on 14/12/19.
//  Copyright (c) 2019 Hélio Mesquita. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ListRoutingLogic {
  func routeToDetail()
}

protocol ListDataPassing {
  var dataStore: ListDataStore? { get }
}

class ListRouter: ListRoutingLogic, ListDataPassing {

  weak var viewController: ListViewController?
  var dataStore: ListDataStore?

  func routeToDetail() {
    let destinationViewController = RepositoryDetailViewController()
    var destinationDataStore = destinationViewController.router?.dataStore
    passDataToList(source: dataStore, destination: &destinationDataStore)
    viewController?.navigationController?.pushViewController(
      destinationViewController, animated: true)
  }

  func passDataToList(source: ListDataStore?, destination: inout RepositoryDetailDataStore?) {
    guard let source = source, var destination = destination else { return }
    destination.repository = source.selectedRepository
  }

}
