//
//  ListModels.swift
//  Swiftmazing
//
//  Created by Hélio Mesquita on 14/12/19.
//  Copyright (c) 2019 Hélio Mesquita. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Visual

enum List {

  class MapRepoViewModel {
    var items: [ListCellViewModel]

    init(repositories: [RepositoryModel]) {
      items = repositories.compactMap { ListCellViewModel(repository: $0) }
    }
  }

  class ListCellViewModel: ListCollectionViewModelProtocol {
    var title: String
    var subtitle: String
    var description: String
    var additionalInfo: String
    var supplementaryInfo: String
    var image: URL?

    var repository: RepositoryModel?

    init(repository: RepositoryModel, supplementaryInfo: String = Text.stars.value) {
      self.title = repository.name
      self.subtitle = repository.owner.name
      self.description = repository.description ?? ""
      self.image = repository.owner.avatar
      self.repository = repository
      self.additionalInfo = repository.stars.kiloFormat
      self.supplementaryInfo = supplementaryInfo
    }
  }

}
