# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:

    runs-on: macoi7

    steps:
    - uses: actions/checkout@v3
    - name: Xcodegen
      run: xcodegen
    - name: Build and test
      run: xcodebuild -scheme Swiftmazing -destination 'platform=iOS Simulator,name=iPhone 14' -workspace Swiftmazing.xcworkspace/ test
